[package]
name = "manifold"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
lume_errors = { path = "../../crates/lume_errors" }
lume_gc = { path = "../../rt/lume_gc", features = ["paranoid"] }
lume_span = { path = "../../crates/lume_span" }

build_stage = { path = "../build_stage" }
clap = { workspace = true }
error_snippet = { workspace = true }
glob = "^0"
owo-colors = { workspace = true }
rayon = "=1.11.0"
regex = { workspace = true }
similar = { version = "=2.7.0", features = ["inline"] }

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["lume_gc"]
