[package]
name = "lume_lexer"
version.workspace = true
edition = "2024"
rust-version.workspace = true

[dependencies]
lume_ast = { path = "../lume_ast" }
lume_span = { path = "../lume_span" }

error_snippet = { workspace = true }
error_snippet_derive = { workspace = true }
