too-many-lines-threshold = 160
disallowed-macros = [
    { path = "std::println", reason = "Use `libftrace::info!` instead", replacement = "libftrace::info!" },
    { path = "std::eprintln", reason = "Use `libftrace::error!` instead", replacement = "libftrace::error!" },
]
