[package]
name = "lume_gc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
lume_trace = { path = "../../crates/lume_trace" }

indexmap = { version = "^2.9" }
mimalloc = { version = "=0.1.48" }

[lib]
doctest = false

[features]
default = ["paranoid"]
paranoid = []
tracing = ["lume_trace/enable"]

[lints]
workspace = true
