[package]
name = "lume_span"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
error_snippet = { workspace = true }
error_snippet_derive = { workspace = true }
fxhash = "^0.2"
indexmap = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }

[lints]
workspace = true
