[package]
name = "lume_macros"
version.workspace = true
edition = "2024"
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2.0.9", features = ["full"] }

[lints]
workspace = true
