[package]
name = "lume_bench"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[lib]
doctest = false

[dependencies]
build_stage = { path = "../build_stage" }
lume_errors = { path = "../../crates/lume_errors" }
lume_session = { path = "../../compiler/lume_session" }

[lints]
workspace = true
