[package]
name = "lume_options"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
ciborium = { version = "=0.2.2" }
serde = { workspace = true, features = ["derive"] }

[lib]
test = false
doctest = false

[lints]
workspace = true
