[package]
name = "lume_demangle"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
lume_errors = { path = "../lume_errors" }

[dev-dependencies]
lume_mangle = { path = "../lume_mangle" }

[lints]
workspace = true
