[package]
name = "lume_runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
backtrace = { version = "=0.3.76" }
lume_gc = { path = "../lume_gc" }
lume_options = { path = "../lume_options" }
lume_rt_metadata = { path = "../lume_rt_metadata" }

owo-colors = { version = "4.2", optional = true, features = ["supports-colors"] }

[lints]
workspace = true

[features]
default = ["color"]
color = ["dep:owo-colors"]
