[package]
name = "lume_hir"
version.workspace = true
edition = "2024"
rust-version.workspace = true

[dependencies]
arc = { path = "../arc" }
lume_ast = { path = "../lume_ast" }
lume_diag = { path = "../lume_diag" }
lume_diag_macros = { path = "../lume_diag_macros" }
lume_macros = { path = "../lume_macros" }
lume_span = { path = "../lume_span" }
lume_state = { path = "../lume_state" }
lume_types = { path = "../lume_types" }

indexmap = { version = "^2.9", features = ["serde"] }
fxhash = "^0.2"
serde = { version = "1.0.219", features = ["serde_derive"] }

[dev-dependencies]
lume_parser = { path = "../lume_parser" }
insta = { version = "1.42.2", features = ["yaml"] }
