[package]
name = "lume_hir"
version.workspace = true
edition = "2024"
rust-version.workspace = true

[dependencies]
arc = { path = "../arc" }
lume_ast = { path = "../lume_ast" }
lume_errors = { path = "../lume_errors" }
lume_macros = { path = "../lume_macros" }
lume_parser = { path = "../lume_parser" }
lume_span = { path = "../lume_span" }
lume_state = { path = "../lume_state" }
lume_types = { path = "../lume_types" }

error_snippet = { workspace = true }
error_snippet_derive = { workspace = true }
indexmap = { version = "^2.9", features = ["serde"] }
rust-embed = { version = "8.7.0", features = ["interpolate-folder-path"] }

[dev-dependencies]
lume_parser = { path = "../lume_parser" }
insta = { version = "1.42.2", features = ["yaml"] }
