[package]
name = "lume_gc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
lume_rt_metadata = { path = "../lume_rt_metadata" }

libftrace = { workspace = true }
indexmap = { workspace = true }
mimalloc = { version = "=0.1.48" }
sysinfo = { version = "=0.37.0" }

[lib]
doctest = false

[features]
paranoid = []

[lints]
workspace = true
