[package]
name = "lume_runner"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
lume_gc = { path = "../lume_gc" }
lume_jit = { path = "../lume_jit" }
lume_mir = { path = "../../compiler/lume_mir" }

env_logger = { version = "=0.11.8", optional = true }
memmap2 = "=0.9.8"
postcard = { version = "=1.1.3", features = ["alloc"] }
serde = { version = "=1.0.219", features = ["derive"] }

[features]
tracing = ["dep:env_logger", "lume_jit/tracing"]

[lints]
workspace = true
