[package]
name = "arc"
version.workspace = true
edition = "2024"
rust-version.workspace = true

[dependencies]
lume_diag = { path = "../lume_diag" }
lume_diag_macros = { path = "../lume_diag_macros" }
fxhash = "^0.2"
glob = "^0"
semver = { version = "^1", features = ["serde"] }
toml_edit = "^0.22"

[dev-dependencies]
insta = { version = "1.42.2" }
