[package]
name = "arc"
version.workspace = true
edition = "2024"
rust-version.workspace = true

[dependencies]
lume_errors = { path = "../lume_errors" }
lume_session = { path = "../lume_session" }
lume_span = { path = "../lume_span" }

error_snippet = { workspace = true }
error_snippet_derive = { workspace = true }
fxhash = "=0.2.1"
git2 = "0.20.2"
glob = "^0"
indexmap = "=2.9.0"
petgraph = "=0.8.2"
rust-embed = { version = "8.7.0", features = ["interpolate-folder-path"] }
semver = { version = "^1" }
tracing = { workspace = true }
url = "=2.5.4"

[dev-dependencies]
insta = { version = "1.42.2" }

[lints]
workspace = true
