[package]
name = "lume_types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
test = false
doctest = false

[dependencies]
lume_errors = { path = "../../crates/lume_errors" }
lume_hir = { path = "../lume_hir" }
lume_session = { path = "../lume_session" }
lume_span = { path = "../../crates/lume_span" }

error_snippet = { workspace = true }
error_snippet_derive = { workspace = true }
indexmap = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }

[lints]
workspace = true
