[package]
name = "lume_types"
version.workspace = true
edition = "2024"
rust-version.workspace = true

[dependencies]
lume_errors = { path = "../lume_errors" }
lume_hir = { path = "../lume_hir" }
lume_session = { path = "../lume_session" }
lume_span = { path = "../lume_span" }

error_snippet = { workspace = true }
error_snippet_derive = { workspace = true }
indexmap = { version = "^2.9" }

[lints]
workspace = true
