[package]
name = "lume_types"
version.workspace = true
edition = "2024"
rust-version.workspace = true

[dependencies]
lume_span = { path = "../lume_span" }

error_snippet = { workspace = true }
error_snippet_derive = { workspace = true }
indexmap = { version = "^2.9", features = ["serde"] }
serde = { version = "1.0.219", features = ["serde_derive"] }
