[package]
name = "lume_errors_test"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
test = false
doctest = false

[dependencies]
lume_errors = { path = "../lume_errors" }

error_snippet = { workspace = true }
insta = { version = "=1.43.1" }
owo-colors = { workspace = true }

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["lume_errors"]
