[package]
name = "lume_errors"
version.workspace = true
edition = "2024"
rust-version.workspace = true

[dependencies]
lume_span = { path = "../lume_span" }

error_snippet = { workspace = true }
error_snippet_derive = { workspace = true }
owo-colors = { workspace = true }

[lints]
workspace = true
