[package]
name = "lume_unification"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
lume_errors = { path = "../../crates/lume_errors" }
lume_hir = { path = "../lume_hir" }
lume_infer = { path = "../lume_infer" }
lume_types = { path = "../lume_types" }
lume_session = { path = "../lume_session" }
lume_span = { path = "../../crates/lume_span" }

error_snippet = { workspace = true }
error_snippet_derive = { workspace = true }
indexmap = { workspace = true }
libftrace = { workspace = true }
lume_architect = { workspace = true }

[lints]
workspace = true
