[package]
name = "lume_diag"
version.workspace = true
edition = "2024"
rust-version.workspace = true

[dependencies]
lume_span = { path = "../lume_span" }

ariadne = "^0.5.1"
indexmap = "2.9.0"
serde = { version = "1.0.219", features = ["serde_derive"] }
